### ISSUE TITLE
Vulnerability detected for Semver

### ISSUE THREAD

**Issue by artola** [expo/expo-webpack-integrations#20]
### Summary

Several packages has pinned `"semver": "7.3.2"`, for example:

https://github.com/expo/expo-cli/blob/af2874cf685e6562c74ab597cdb099750c84a3fd/packages/image-utils/package.json#L39

See: [`semver vulnerable to Regular Expression Denial of Service`](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw) for more details.

```
semver: 7.3.2
   ├─ ID: 1093264
   ├─ Issue: semver vulnerable to Regular Expression Denial of Service
   ├─ URL: https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
   ├─ Severity: moderate
   ├─ Vulnerable Versions: >=7.0.0 <7.5.2
   ├─ Patched Versions: >=7.5.2
   └─ Recommendation: Upgrade to version 7.5.2 or later
 ```

### Environment

`@expo/prebuild-config@npm:6.2.6`=> `@expo/image-utils@npm:0.3.2`

### Please specify your device/emulator/simulator platform, model and version

NA

### Reproducible demo or steps to reproduce from a blank project

Check vulnerabilities, e.g.: `yarn audit`.

**Comment by byCedric** [comment]
This has been merged and released in `@expo/webpack-config@19.0.1`. See [CHANGELOG](https://github.com/expo/expo-webpack-integrations/blob/main/packages/webpack-config/CHANGELOG.md#1901---2024-01-17)
